# Generated by Django 5.0.2 on 2024-03-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collage_image', models.ImageField(upload_to='collages/')),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
